### ISSUE TITLE
withLoadStateFooter无效

### ISSUE THREAD

**Issue by liumengbiao** [Colaman0/PagingDemo#1]
我在fragment里面使用加载更多的底部布局不出现。这应该是是什么问题。

**Comment by Colaman0** [comment]
建议先查看一下source中key是否准确，以及adapter是否设置对，应该把withLoadStateFooter返回的adapter设置给recyclerview

**Comment by liumengbiao** [comment]
recyclerview.adapter = mAdapter.withLoadStateHeader(ExampleLoadindStateAdapter())
适配器设置肯定没有问题，source我用的是你的demo的source。我怀疑自己的source有问题，但是只有copy进入我的工程，就失效了。头疼一天了。非常想用paging3做加载更多的效果。

**Comment by Colaman0** [comment]
> ```
> recyclerview.adapter = mAdapter.withLoadStateHeader(ExampleLoadindStateAdapter())
> ```
> 
> [，来源]，来源[来源]，[复制]，]，]，头疼一天了。[页3]

或者你把项目放到github，我晚上帮你看一下

**Comment by TakeNotes2019** [comment]
这个问题 我用java 写的 也困扰了许久，然后看到了那条回复，终于搞定，这句话“应该把withLoadStateFooter返回的adapter设置给recyclerview”， 现在我不知道如何 更新 ，增加，删除单挑item 。。。由于对kt 及携程 不太了解 十分头疼， 项

**Comment by TakeNotes2019** [comment]
我使用的是官网 RX 那格逻辑 ，
数据源 是这样写的          mPagingData = PagingRx.getFlowable(pager);
        PagingRx.cachedIn(mPagingData, viewModelScope);
        PagingLiveData.cachedIn(PagingLiveData.getLiveData(pager), viewModelScope);

**Comment by Colaman0** [comment]
Paging3暂时不支持增删改这种操作，删除可以通过自己做一层过滤，比如rxjava就用filter操作符去过滤掉想要的数据，至于其他操作可能后续版本会支持。相当于把原有数据重新过滤然后发射，然后用diffutil更新。你也可以去看回我那篇文章，我有提到关于这个功能的实现。
